### ISSUE TITLE
Milestone1 - Checklist

### ISSUE THREAD

**Issue by everittB** [UBC-MDS/AutoTransformPy#4]
##### Tasks to Complete  
- [x] Update README.md and README.txt  
- [x] AutoTransformPy folder structure setup  (Brenden/Alycia)
- [x] Rotate function test suite (Brenden)
  - [x]  Python
  - [x]  R  
- [x] Mirror function test suite  (Alycia)
  - [x]  Python
  - [x]  R  
- [x] Translate function test suite  (Rayce)
  - [x]  Python
  - [x]  R
